import Head from "next/head";
import Header from "../components/Header";
import CountryCard from "../components/CountryCard";
import axios from "axios";
import { useEffect, useState } from "react";

export default function Home() {
  const [AllCountries, setAllCountries] = useState(null);

  useEffect(() => {
    const AllCountries = async () => {
      const data = await (
        await axios.get("https://restcountries.eu/rest/v2/all")
      ).data;
      setAllCountries(data);
    };
    AllCountries();
  }, []);

  // console.log(AllCountries);

  return (
    <>
      <div
        className={`bg-[#fafafa] dark:bg-[#202c37] bg-opacity-100  text-[#111517] dark:text-[#ffffff]`}
      >
        <Head>
          <title>Where In The World</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <>
          
          <Header />

          <CountryCard AllCountries={AllCountries} />

          {/* {all.map((array) => (<h1 key={array.name} className="text-[4rem] ">{array.name}</h1>))} */}
        </>

        <footer></footer>
      </div>
    </>
  );
}
