import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Where In The World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <h1 className="text-[4rem]">Hello World</h1>
      </main>

      <footer >
       
      </footer>
    </div>
  )
}
